[Procheta | Nidhi] Refactor. and Integrate. TravelClassList
hariharanweb/mobility-sample-frontend pull request #58
Opened 2023-03-14 12:59 UTC by prochetab1999

2023-03-15 15:57 UTC, hariharanweb commented on src/components/Catalog.js
> +        {item?.travelClass && (
Item cannot be null

2023-03-15 15:57 UTC, hariharanweb commented on src/components/Catalog.js
> +      {' '}
Why do you need empty

2023-03-15 15:57 UTC, hariharanweb commented on src/components/Item.js
> +        <div style={{
Use grid

2023-03-15 16:02 UTC, hariharanweb requested changes

2023-03-15 16:02 UTC, hariharanweb commented on src/components/Item.js
> +  const containerStyle = 'item-with-border';
Remove this variable

2023-03-15 16:02 UTC, hariharanweb commented on src/components/Item.js
> +          <Typography variant="body1" style={{ fontSize: 'small', fontWeight: '500', paddingLeft: '1px' }}>
Use attribute than style.

2023-03-15 16:02 UTC, hariharanweb commented on src/components/TravelClass.js
> +        <Typography fontWeight={500}>{travelClass?.availability}</Typography>
Handle availability not there

2023-03-20 07:01 UTC, nidhirajput13 commented on src/components/Catalog.js
> +      {' '}
Fixed

2023-03-20 07:02 UTC, nidhirajput13 commented on src/components/Item.js
> +        <div style={{
Fixed

2023-03-20 07:03 UTC, nidhirajput13 commented on src/components/TravelClass.js
> +        <Typography fontWeight={500}>{travelClass?.availability}</Typography>
Working fine

2023-03-20 07:13 UTC, nidhirajput13 commented on src/components/Item.js
> +          <Typography variant="body1" style={{ fontSize: 'small', fontWeight: '500', paddingLeft: '1px' }}>
Fixed

2023-03-20 07:49 UTC, merged